= Module 06 - OpenShift Virtualization in the Cloud

include::vars.adoc[]

== Introduction

By harnessing the power of Red Hat's cloud partners, customers can benefit by extending their OpenShift Virtualization deployment in a truly hybrid fashion. This module is mostly instructive, but includes both video demonstrations and interactive demostrations of OpenShift Virtualization running in our various cloud partners. By extending their virtualization solution to their cloud provider of choice, a customer can often overcome many of the challenges that lead them to seek out cloud infrastructure to begin with. They can scale up or down on demand, they can have joint support and unified management of their solution, and take advantage of flexible commit spend options instead of hosting their infrastructure on site. 

See the sections below to learn more about each of the cloud providers that we partner with, and how they support OpenShift Virtualization.

== Amazon Web Services

Red Hat OpenShift Virtualization is *Generally Available* in both self-managed Red Hat OpenShift, and fully-managed Red Hat OpenShift on AWS (ROSA) clusters in Amazon Web Services, simply by installing the Virtualization Operator, and adding bare metal compute nodes to your cluster.

*Video Demo: Configuring a ROSA cluster to run OpenShift Virtualization*

++++
<iframe width="800" height="480" src="https://www.youtube.com/embed/wBtY3tvjtIU" title="Configuring OpenShift Virtualization to run on Red Hat OpenShift Service on AWS" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

*Video Demo: Deploying Virtual Machines in OpenShift Virtualization on ROSA*

++++
<iframe width="800" height="480" src="https://www.youtube.com/embed/7EpmmUIhQ7c" title="Deploying Virtual machines in OpenShift Virtualization on Red Hat OpenShift Service on AWS" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
++++

== Google Cloud

Red Hat OpenShift Virtualization is now available as a *Technology Preview* in https://www.redhat.com/en/blog/red-hat-openshift-virtualization-google-cloud[Google Cloud^] as a part of Red Hat OpenShift Dedicated:

*Arcade Interactive Demo: Deploy Virtual Machines in OpenShift Virtualization on Red Hat OpenShift Dedicated*
 
++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(60.8805% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/HleIaKgn1Iuf9SrJSt3S?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Deploy Virtual Machines in OpenShift Virtualization on Red Hat OpenShift Dedicated" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

== IBM Cloud

Red Hat OpenShift Virtualization is now *Generally Available* in https://www.ibm.com/new/announcements/red-hat-openshift-virtualization-is-now-available-on-ibm-cloud2[IBM Cloud^]


== Microsoft Azure

Red Hat OpenShift Virtualization is now *Generally Available* on https://learn.microsoft.com/en-us/azure/openshift/howto-create-openshift-virtualization[Microsoft Azure^], as a part of the Azure Red Hat OpenShift (ARO) fully-managed solution.

*Arcade Interactive Demo: Azure Red Hat OpenShift Virtualization Demo*

++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(56.25% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/qMIbsgMch6Hrhz5ZI0Fr?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Azure Red Hat Openshift Virtualization Demo" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

*Arcade Interactive Demo: Effortless VM Deployment with Azure Red Hat OpenShift*

++++
<!--ARCADE EMBED START--><div style="position: relative; padding-bottom: calc(53.5053% + 41px); height: 0px; width: 100%;"><iframe src="https://demo.arcade.software/ZcUp0s4iubfGRYc7GZUY?embed&embed_mobile=tab&embed_desktop=inline&show_copy_link=true" title="Effortless VM Deployment with Azure Red HatOpenShift" frameborder="0" loading="lazy" webkitallowfullscreen mozallowfullscreen allowfullscreen allow="clipboard-write" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; color-scheme: light;" ></iframe></div><!--ARCADE EMBED END-->
++++

== Oracle Cloud

Red Hat OpenShift Virtualization is now *Generally Available* on https://blogs.oracle.com/cloud-infrastructure/red-hat-openshift-virtualization-available-on-oci[Oracle Cloud^].


== Conclusion

Having Red Hat OpenShift Virtualization available in our cloud partner environments allows for our customers to extend their datacenters into a fully hybrid scenario for both Virtual Machines and Containers. This enables resilient applications and redundant infrastructures across multiple regions and availability zones to ensure that services are always available.
